---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My hello Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is ðŸ˜Ž

- Group A:
    - Caddy:
        href: localhost:2019
        description: Caddy reverse proxy
        container: caddy
